// <auto-generated/>
// This file is automatically generated from VcpFeatureData.json
// Do not edit this file directly. Instead, edit VcpFeatureData.json and regenerate.

namespace DDCSwitch;

public partial class VcpFeature
{
    // ===== GENERATED VCP FEATURES =====

    // ===== PRESET FEATURES =====

    /// <summary>
    /// Degauss (VCP 0x01)
    /// </summary>
    public static VcpFeature Degauss => new(0x01, "degauss", "Degauss", VcpFeatureType.WriteOnly, VcpFeatureCategory.Preset, false);

    /// <summary>
    /// New control value (VCP 0x02)
    /// </summary>
    public static VcpFeature NewControlValue => new(0x02, "new-control-value", "New control value", VcpFeatureType.ReadWrite, VcpFeatureCategory.Preset, false);

    /// <summary>
    /// Soft controls (VCP 0x03)
    /// </summary>
    public static VcpFeature SoftControls => new(0x03, "soft-controls", "Soft controls", VcpFeatureType.ReadWrite, VcpFeatureCategory.Preset, false);

    /// <summary>
    /// Restore factory defaults (VCP 0x04)
    /// </summary>
    public static VcpFeature RestoreDefaults => new(0x04, "restore-defaults", "Restore factory defaults", VcpFeatureType.WriteOnly, VcpFeatureCategory.Preset, false, "factory-reset");

    /// <summary>
    /// Restore factory brightness/contrast defaults (VCP 0x05)
    /// </summary>
    public static VcpFeature RestoreBrightnessContrastDefaults => new(0x05, "restore-brightness-contrast", "Restore factory brightness/contrast defaults", VcpFeatureType.WriteOnly, VcpFeatureCategory.Preset, false);

    /// <summary>
    /// Restore factory geometry defaults (VCP 0x06)
    /// </summary>
    public static VcpFeature RestoreGeometryDefaults => new(0x06, "restore-geometry", "Restore factory geometry defaults", VcpFeatureType.WriteOnly, VcpFeatureCategory.Preset, false);

    /// <summary>
    /// Restore factory color defaults (VCP 0x08)
    /// </summary>
    public static VcpFeature RestoreColorDefaults => new(0x08, "restore-color", "Restore factory color defaults", VcpFeatureType.WriteOnly, VcpFeatureCategory.Preset, false);

    /// <summary>
    /// Restore factory TV defaults (VCP 0x0A)
    /// </summary>
    public static VcpFeature RestoreTVDefaults => new(0x0A, "restore-tv-defaults", "Restore factory TV defaults", VcpFeatureType.WriteOnly, VcpFeatureCategory.Preset, false);


    // ===== COLORCONTROL FEATURES =====

    /// <summary>
    /// Color temperature increment (VCP 0x0B)
    /// </summary>
    public static VcpFeature ColorTemperatureIncrement => new(0x0B, "color-temp-increment", "Color temperature increment", VcpFeatureType.ReadOnly, VcpFeatureCategory.ColorControl, false);

    /// <summary>
    /// Color temperature request (VCP 0x0C)
    /// </summary>
    public static VcpFeature ColorTemperatureRequest => new(0x0C, "color-temp-request", "Color temperature request", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, false, "color-temp");

    /// <summary>
    /// Video gain: Red (VCP 0x16)
    /// </summary>
    public static VcpFeature RedGain => new(0x16, "red-gain", "Video gain: Red", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true, "red");

    /// <summary>
    /// User color vision compensation (VCP 0x17)
    /// </summary>
    public static VcpFeature UserColorVisionCompensation => new(0x17, "user-color-vision-compensation", "User color vision compensation", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// Video gain: Green (VCP 0x18)
    /// </summary>
    public static VcpFeature GreenGain => new(0x18, "green-gain", "Video gain: Green", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true, "green");

    /// <summary>
    /// Video gain: Blue (VCP 0x1A)
    /// </summary>
    public static VcpFeature BlueGain => new(0x1A, "blue-gain", "Video gain: Blue", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true, "blue");

    /// <summary>
    /// 6 axis saturation: Red (VCP 0x59)
    /// </summary>
    public static VcpFeature SixAxisSaturationRed => new(0x59, "6-axis-saturation-red", "6 axis saturation: Red", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// 6 axis saturation: Yellow (VCP 0x5A)
    /// </summary>
    public static VcpFeature SixAxisSaturationYellow => new(0x5A, "6-axis-saturation-yellow", "6 axis saturation: Yellow", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// 6 axis saturation: Green (VCP 0x5B)
    /// </summary>
    public static VcpFeature SixAxisSaturationGreen => new(0x5B, "6-axis-saturation-green", "6 axis saturation: Green", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// 6 axis saturation: Cyan (VCP 0x5C)
    /// </summary>
    public static VcpFeature SixAxisSaturationCyan => new(0x5C, "6-axis-saturation-cyan", "6 axis saturation: Cyan", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// 6 axis saturation: Blue (VCP 0x5D)
    /// </summary>
    public static VcpFeature SixAxisSaturationBlue => new(0x5D, "6-axis-saturation-blue", "6 axis saturation: Blue", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// 6 axis saturation: Magenta (VCP 0x5E)
    /// </summary>
    public static VcpFeature SixAxisSaturationMagenta => new(0x5E, "6-axis-saturation-magenta", "6 axis saturation: Magenta", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// Backlight Level: White (VCP 0x6B)
    /// </summary>
    public static VcpFeature BacklightLevelWhite => new(0x6B, "backlight-level-white", "Backlight Level: White", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// Video black level: Red (VCP 0x6C)
    /// </summary>
    public static VcpFeature RedBlackLevel => new(0x6C, "red-black-level", "Video black level: Red", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// Backlight Level: Red (VCP 0x6D)
    /// </summary>
    public static VcpFeature BacklightLevelRed => new(0x6D, "backlight-level-red", "Backlight Level: Red", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// Video black level: Green (VCP 0x6E)
    /// </summary>
    public static VcpFeature GreenBlackLevel => new(0x6E, "green-black-level", "Video black level: Green", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// Backlight Level: Green (VCP 0x6F)
    /// </summary>
    public static VcpFeature BacklightLevelGreen => new(0x6F, "backlight-level-green", "Backlight Level: Green", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// Video black level: Blue (VCP 0x70)
    /// </summary>
    public static VcpFeature BlueBlackLevel => new(0x70, "blue-black-level", "Video black level: Blue", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// Backlight Level: Blue (VCP 0x71)
    /// </summary>
    public static VcpFeature BacklightLevelBlue => new(0x71, "backlight-level-blue", "Backlight Level: Blue", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// Gamma (VCP 0x72)
    /// </summary>
    public static VcpFeature Gamma => new(0x72, "gamma", "Gamma", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, false);

    /// <summary>
    /// Color Saturation (VCP 0x8A)
    /// </summary>
    public static VcpFeature ColorSaturation => new(0x8A, "color-saturation", "Color Saturation", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true, "saturation", "sat");

    /// <summary>
    /// Hue (VCP 0x90)
    /// </summary>
    public static VcpFeature Hue => new(0x90, "hue", "Hue", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// 6 axis hue control: Red (VCP 0x9B)
    /// </summary>
    public static VcpFeature SixAxisHueRed => new(0x9B, "6-axis-hue-red", "6 axis hue control: Red", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// 6 axis hue control: Yellow (VCP 0x9C)
    /// </summary>
    public static VcpFeature SixAxisHueYellow => new(0x9C, "6-axis-hue-yellow", "6 axis hue control: Yellow", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// 6 axis hue control: Green (VCP 0x9D)
    /// </summary>
    public static VcpFeature SixAxisHueGreen => new(0x9D, "6-axis-hue-green", "6 axis hue control: Green", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// 6 axis hue control: Cyan (VCP 0x9E)
    /// </summary>
    public static VcpFeature SixAxisHueCyan => new(0x9E, "6-axis-hue-cyan", "6 axis hue control: Cyan", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// 6 axis hue control: Blue (VCP 0x9F)
    /// </summary>
    public static VcpFeature SixAxisHueBlue => new(0x9F, "6-axis-hue-blue", "6 axis hue control: Blue", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);

    /// <summary>
    /// 6 axis hue control: Magenta (VCP 0xA0)
    /// </summary>
    public static VcpFeature SixAxisHueMagenta => new(0xA0, "6-axis-hue-magenta", "6 axis hue control: Magenta", VcpFeatureType.ReadWrite, VcpFeatureCategory.ColorControl, true);


    // ===== GEOMETRY FEATURES =====

    /// <summary>
    /// Clock (VCP 0x0E)
    /// </summary>
    public static VcpFeature Clock => new(0x0E, "clock", "Clock", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Horizontal Position (Phase) (VCP 0x20)
    /// </summary>
    public static VcpFeature HorizontalPosition => new(0x20, "h-position", "Horizontal Position (Phase)", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false, "h-pos");

    /// <summary>
    /// Horizontal Size (VCP 0x22)
    /// </summary>
    public static VcpFeature HorizontalSize => new(0x22, "h-size", "Horizontal Size", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Horizontal Pincushion (VCP 0x24)
    /// </summary>
    public static VcpFeature HorizontalPincushion => new(0x24, "h-pincushion", "Horizontal Pincushion", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Horizontal Pincushion Balance (VCP 0x26)
    /// </summary>
    public static VcpFeature HorizontalPincushionBalance => new(0x26, "h-pincushion-balance", "Horizontal Pincushion Balance", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Horizontal Convergence R/B (VCP 0x28)
    /// </summary>
    public static VcpFeature HorizontalConvergenceRB => new(0x28, "h-convergence-rb", "Horizontal Convergence R/B", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Horizontal Convergence M/G (VCP 0x29)
    /// </summary>
    public static VcpFeature HorizontalConvergenceMG => new(0x29, "h-convergence-mg", "Horizontal Convergence M/G", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Horizontal Linearity (VCP 0x2A)
    /// </summary>
    public static VcpFeature HorizontalLinearity => new(0x2A, "h-linearity", "Horizontal Linearity", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Horizontal Linearity Balance (VCP 0x2C)
    /// </summary>
    public static VcpFeature HorizontalLinearityBalance => new(0x2C, "h-linearity-balance", "Horizontal Linearity Balance", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Vertical Position (Phase) (VCP 0x30)
    /// </summary>
    public static VcpFeature VerticalPosition => new(0x30, "v-position", "Vertical Position (Phase)", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false, "v-pos");

    /// <summary>
    /// Vertical Size (VCP 0x32)
    /// </summary>
    public static VcpFeature VerticalSize => new(0x32, "v-size", "Vertical Size", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Vertical Pincushion (VCP 0x34)
    /// </summary>
    public static VcpFeature VerticalPincushion => new(0x34, "v-pincushion", "Vertical Pincushion", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Vertical Pincushion Balance (VCP 0x36)
    /// </summary>
    public static VcpFeature VerticalPincushionBalance => new(0x36, "v-pincushion-balance", "Vertical Pincushion Balance", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Vertical Convergence R/B (VCP 0x38)
    /// </summary>
    public static VcpFeature VerticalConvergenceRB => new(0x38, "v-convergence-rb", "Vertical Convergence R/B", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Vertical Convergence M/G (VCP 0x39)
    /// </summary>
    public static VcpFeature VerticalConvergenceMG => new(0x39, "v-convergence-mg", "Vertical Convergence M/G", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Vertical Linearity (VCP 0x3A)
    /// </summary>
    public static VcpFeature VerticalLinearity => new(0x3A, "v-linearity", "Vertical Linearity", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Vertical Linearity Balance (VCP 0x3C)
    /// </summary>
    public static VcpFeature VerticalLinearityBalance => new(0x3C, "v-linearity-balance", "Vertical Linearity Balance", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Clock Phase (VCP 0x3E)
    /// </summary>
    public static VcpFeature ClockPhase => new(0x3E, "clock-phase", "Clock Phase", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false, "phase");

    /// <summary>
    /// Horizontal Parallelogram (VCP 0x40)
    /// </summary>
    public static VcpFeature HorizontalParallelogram => new(0x40, "horizontal-parallelogram", "Horizontal Parallelogram", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Vertical Parallelogram (VCP 0x41)
    /// </summary>
    public static VcpFeature VerticalParallelogram => new(0x41, "vertical-parallelogram", "Vertical Parallelogram", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Horizontal Keystone (VCP 0x42)
    /// </summary>
    public static VcpFeature HorizontalKeystone => new(0x42, "horizontal-keystone", "Horizontal Keystone", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Vertical Keystone (VCP 0x43)
    /// </summary>
    public static VcpFeature VerticalKeystone => new(0x43, "vertical-keystone", "Vertical Keystone", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Rotation (VCP 0x44)
    /// </summary>
    public static VcpFeature Rotation => new(0x44, "rotation", "Rotation", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Top Corner Flare (VCP 0x46)
    /// </summary>
    public static VcpFeature TopCornerFlare => new(0x46, "top-corner-flare", "Top Corner Flare", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Top Corner Hook (VCP 0x48)
    /// </summary>
    public static VcpFeature TopCornerHook => new(0x48, "top-corner-hook", "Top Corner Hook", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Bottom Corner Flare (VCP 0x4A)
    /// </summary>
    public static VcpFeature BottomCornerFlare => new(0x4A, "bottom-corner-flare", "Bottom Corner Flare", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Bottom Corner Hook (VCP 0x4C)
    /// </summary>
    public static VcpFeature BottomCornerHook => new(0x4C, "bottom-corner-hook", "Bottom Corner Hook", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Window Position(TL_X) (VCP 0x95)
    /// </summary>
    public static VcpFeature WindowPositionTLX => new(0x95, "window-position-tl-x", "Window Position(TL_X)", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Window Position(TL_Y) (VCP 0x96)
    /// </summary>
    public static VcpFeature WindowPositionTLY => new(0x96, "window-position-tl-y", "Window Position(TL_Y)", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Window Position(BR_X) (VCP 0x97)
    /// </summary>
    public static VcpFeature WindowPositionBRX => new(0x97, "window-position-br-x", "Window Position(BR_X)", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Window Position(BR_Y) (VCP 0x98)
    /// </summary>
    public static VcpFeature WindowPositionBRY => new(0x98, "window-position-br-y", "Window Position(BR_Y)", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);

    /// <summary>
    /// Window control on/off (VCP 0x99)
    /// </summary>
    public static VcpFeature WindowControlOnOff => new(0x99, "window-control-on-off", "Window control on/off", VcpFeatureType.ReadWrite, VcpFeatureCategory.Geometry, false);


    // ===== IMAGEADJUSTMENT FEATURES =====

    /// <summary>
    /// Brightness control (VCP 0x10)
    /// </summary>
    public static VcpFeature Brightness => new(0x10, "brightness", "Brightness control", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, true, "bright");

    /// <summary>
    /// Flesh tone enhancement (VCP 0x11)
    /// </summary>
    public static VcpFeature FleshToneEnhancement => new(0x11, "flesh-tone-enhancement", "Flesh tone enhancement", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, false);

    /// <summary>
    /// Contrast control (VCP 0x12)
    /// </summary>
    public static VcpFeature Contrast => new(0x12, "contrast", "Contrast control", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, true);

    /// <summary>
    /// Backlight control (VCP 0x13)
    /// </summary>
    public static VcpFeature Backlight => new(0x13, "backlight", "Backlight control", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, true);

    /// <summary>
    /// Select color preset (VCP 0x14)
    /// </summary>
    public static VcpFeature SelectColorPreset => new(0x14, "select-color-preset", "Select color preset", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, false, "color-preset");

    /// <summary>
    /// Focus (VCP 0x1C)
    /// </summary>
    public static VcpFeature Focus => new(0x1C, "focus", "Focus", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, true);

    /// <summary>
    /// Auto setup (VCP 0x1E)
    /// </summary>
    public static VcpFeature AutoSetup => new(0x1E, "auto-setup", "Auto setup", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, false);

    /// <summary>
    /// Auto color setup (VCP 0x1F)
    /// </summary>
    public static VcpFeature AutoColorSetup => new(0x1F, "auto-color-setup", "Auto color setup", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, false);

    /// <summary>
    /// Gray scale expansion (VCP 0x2E)
    /// </summary>
    public static VcpFeature GrayScaleExpansion => new(0x2E, "gray-scale-expansion", "Gray scale expansion", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, false);

    /// <summary>
    /// Horizontal Moire (VCP 0x56)
    /// </summary>
    public static VcpFeature HorizontalMoire => new(0x56, "horizontal-moire", "Horizontal Moire", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, true);

    /// <summary>
    /// Vertical Moire (VCP 0x58)
    /// </summary>
    public static VcpFeature VerticalMoire => new(0x58, "vertical-moire", "Vertical Moire", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, true);

    /// <summary>
    /// Input source selection (VCP 0x60)
    /// </summary>
    public static VcpFeature InputSource => new(0x60, "input", "Input source selection", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, false, "source");

    /// <summary>
    /// Adjust Focal Plane (VCP 0x7A)
    /// </summary>
    public static VcpFeature AdjustFocalPlane => new(0x7A, "adjust-focal-plane", "Adjust Focal Plane", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, true);

    /// <summary>
    /// Adjust Zoom (VCP 0x7C)
    /// </summary>
    public static VcpFeature AdjustZoom => new(0x7C, "adjust-zoom", "Adjust Zoom", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, true);

    /// <summary>
    /// Trapezoid (VCP 0x7E)
    /// </summary>
    public static VcpFeature Trapezoid => new(0x7E, "trapezoid", "Trapezoid", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, true);

    /// <summary>
    /// Keystone (VCP 0x80)
    /// </summary>
    public static VcpFeature Keystone => new(0x80, "keystone", "Keystone", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, true);

    /// <summary>
    /// Horizontal Mirror (Flip) (VCP 0x82)
    /// </summary>
    public static VcpFeature HorizontalMirror => new(0x82, "horizontal-mirror", "Horizontal Mirror (Flip)", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, false);

    /// <summary>
    /// Vertical Mirror (Flip) (VCP 0x84)
    /// </summary>
    public static VcpFeature VerticalMirror => new(0x84, "vertical-mirror", "Vertical Mirror (Flip)", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, false);

    /// <summary>
    /// Display Scaling (VCP 0x86)
    /// </summary>
    public static VcpFeature DisplayScaling => new(0x86, "display-scaling", "Display Scaling", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, false);

    /// <summary>
    /// Sharpness control (VCP 0x87)
    /// </summary>
    public static VcpFeature Sharpness => new(0x87, "sharpness", "Sharpness control", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, true, "sharp");

    /// <summary>
    /// Velocity Scan Modulation (VCP 0x88)
    /// </summary>
    public static VcpFeature VelocityScanModulation => new(0x88, "velocity-scan-modulation", "Velocity Scan Modulation", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, true);

    /// <summary>
    /// TV Sharpness (VCP 0x8C)
    /// </summary>
    public static VcpFeature TVSharpness => new(0x8C, "tv-sharpness", "TV Sharpness", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, true);

    /// <summary>
    /// TV Contrast (VCP 0x8E)
    /// </summary>
    public static VcpFeature TVContrast => new(0x8E, "tv-contrast", "TV Contrast", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, true);

    /// <summary>
    /// TV Black level/Luminesence (VCP 0x92)
    /// </summary>
    public static VcpFeature TVBlackLevel => new(0x92, "tv-black-level", "TV Black level/Luminesence", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, true);

    /// <summary>
    /// Window background (VCP 0x9A)
    /// </summary>
    public static VcpFeature WindowBackground => new(0x9A, "window-background", "Window background", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, true);

    /// <summary>
    /// Auto setup on/off (VCP 0xA2)
    /// </summary>
    public static VcpFeature AutoSetupOnOff => new(0xA2, "auto-setup-on-off", "Auto setup on/off", VcpFeatureType.WriteOnly, VcpFeatureCategory.ImageAdjustment, false);

    /// <summary>
    /// Window mask control (VCP 0xA4)
    /// </summary>
    public static VcpFeature WindowMaskControl => new(0xA4, "window-mask-control", "Window mask control", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, false);

    /// <summary>
    /// Change the selected window (VCP 0xA5)
    /// </summary>
    public static VcpFeature ChangeSelectedWindow => new(0xA5, "change-selected-window", "Change the selected window", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, false);

    /// <summary>
    /// Screen Orientation (VCP 0xAA)
    /// </summary>
    public static VcpFeature ScreenOrientation => new(0xAA, "screen-orientation", "Screen Orientation", VcpFeatureType.ReadOnly, VcpFeatureCategory.ImageAdjustment, false, "orientation");

    /// <summary>
    /// Stereo video mode (VCP 0xD4)
    /// </summary>
    public static VcpFeature StereoVideoMode => new(0xD4, "stereo-video-mode", "Stereo video mode", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, false);

    /// <summary>
    /// Scan mode (VCP 0xDA)
    /// </summary>
    public static VcpFeature ScanMode => new(0xDA, "scan-mode", "Scan mode", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, false);

    /// <summary>
    /// Image Mode (VCP 0xDB)
    /// </summary>
    public static VcpFeature ImageMode => new(0xDB, "image-mode", "Image Mode", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, false, "mode");

    /// <summary>
    /// Display Mode (VCP 0xDC)
    /// </summary>
    public static VcpFeature DisplayMode => new(0xDC, "display-mode", "Display Mode", VcpFeatureType.ReadWrite, VcpFeatureCategory.ImageAdjustment, false);


    // ===== MISCELLANEOUS FEATURES =====

    /// <summary>
    /// Active control (VCP 0x52)
    /// </summary>
    public static VcpFeature ActiveControl => new(0x52, "active-control", "Active control", VcpFeatureType.ReadOnly, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Performance Preservation (VCP 0x54)
    /// </summary>
    public static VcpFeature PerformancePreservation => new(0x54, "performance-preservation", "Performance Preservation", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Ambient light sensor (VCP 0x66)
    /// </summary>
    public static VcpFeature AmbientLightSensor => new(0x66, "ambient-light-sensor", "Ambient light sensor", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// LUT Size (VCP 0x73)
    /// </summary>
    public static VcpFeature LUTSize => new(0x73, "lut-size", "LUT Size", VcpFeatureType.ReadOnly, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Single point LUT operation (VCP 0x74)
    /// </summary>
    public static VcpFeature SinglePointLUTOperation => new(0x74, "single-point-lut-operation", "Single point LUT operation", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Block LUT operation (VCP 0x75)
    /// </summary>
    public static VcpFeature BlockLUTOperation => new(0x75, "block-lut-operation", "Block LUT operation", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Remote Procedure Call (VCP 0x76)
    /// </summary>
    public static VcpFeature RemoteProcedureCall => new(0x76, "remote-procedure-call", "Remote Procedure Call", VcpFeatureType.WriteOnly, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Display Identification Operation (VCP 0x78)
    /// </summary>
    public static VcpFeature DisplayIdentificationOperation => new(0x78, "display-identification-operation", "Display Identification Operation", VcpFeatureType.ReadOnly, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// TV Channel Up/Down (VCP 0x8B)
    /// </summary>
    public static VcpFeature TVChannelUpDown => new(0x8B, "tv-channel-up-down", "TV Channel Up/Down", VcpFeatureType.WriteOnly, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Horizontal frequency (VCP 0xAC)
    /// </summary>
    public static VcpFeature HorizontalFrequency => new(0xAC, "horizontal-frequency", "Horizontal frequency", VcpFeatureType.ReadOnly, VcpFeatureCategory.Miscellaneous, false, "h-freq");

    /// <summary>
    /// Vertical frequency (VCP 0xAE)
    /// </summary>
    public static VcpFeature VerticalFrequency => new(0xAE, "vertical-frequency", "Vertical frequency", VcpFeatureType.ReadOnly, VcpFeatureCategory.Miscellaneous, false, "v-freq");

    /// <summary>
    /// Settings (VCP 0xB0)
    /// </summary>
    public static VcpFeature Settings => new(0xB0, "settings", "Settings", VcpFeatureType.WriteOnly, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Flat panel sub-pixel layout (VCP 0xB2)
    /// </summary>
    public static VcpFeature FlatPanelSubPixelLayout => new(0xB2, "flat-panel-sub-pixel-layout", "Flat panel sub-pixel layout", VcpFeatureType.ReadOnly, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Source Timing Mode (VCP 0xB4)
    /// </summary>
    public static VcpFeature SourceTimingMode => new(0xB4, "source-timing-mode", "Source Timing Mode", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Display technology type (VCP 0xB6)
    /// </summary>
    public static VcpFeature DisplayTechnologyType => new(0xB6, "display-technology-type", "Display technology type", VcpFeatureType.ReadOnly, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Monitor status (VCP 0xB7)
    /// </summary>
    public static VcpFeature MonitorStatus => new(0xB7, "monitor-status", "Monitor status", VcpFeatureType.ReadOnly, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Packet count (VCP 0xB8)
    /// </summary>
    public static VcpFeature PacketCount => new(0xB8, "packet-count", "Packet count", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Monitor X origin (VCP 0xB9)
    /// </summary>
    public static VcpFeature MonitorXOrigin => new(0xB9, "monitor-x-origin", "Monitor X origin", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Monitor Y origin (VCP 0xBA)
    /// </summary>
    public static VcpFeature MonitorYOrigin => new(0xBA, "monitor-y-origin", "Monitor Y origin", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Header error count (VCP 0xBB)
    /// </summary>
    public static VcpFeature HeaderErrorCount => new(0xBB, "header-error-count", "Header error count", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Body CRC error count (VCP 0xBC)
    /// </summary>
    public static VcpFeature BodyCRCErrorCount => new(0xBC, "body-crc-error-count", "Body CRC error count", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Client ID (VCP 0xBD)
    /// </summary>
    public static VcpFeature ClientID => new(0xBD, "client-id", "Client ID", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Link control (VCP 0xBE)
    /// </summary>
    public static VcpFeature LinkControl => new(0xBE, "link-control", "Link control", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Display usage time (VCP 0xC0)
    /// </summary>
    public static VcpFeature DisplayUsageTime => new(0xC0, "display-usage-time", "Display usage time", VcpFeatureType.ReadOnly, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Display descriptor length (VCP 0xC2)
    /// </summary>
    public static VcpFeature DisplayDescriptorLength => new(0xC2, "display-descriptor-length", "Display descriptor length", VcpFeatureType.ReadOnly, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Transmit display descriptor (VCP 0xC3)
    /// </summary>
    public static VcpFeature TransmitDisplayDescriptor => new(0xC3, "transmit-display-descriptor", "Transmit display descriptor", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Enable display of 'display descriptor' (VCP 0xC4)
    /// </summary>
    public static VcpFeature EnableDisplayOfDisplayDescriptor => new(0xC4, "enable-display-of-display-descriptor", "Enable display of 'display descriptor'", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Application enable key (VCP 0xC6)
    /// </summary>
    public static VcpFeature ApplicationEnableKey => new(0xC6, "application-enable-key", "Application enable key", VcpFeatureType.ReadOnly, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Display controller type (VCP 0xC8)
    /// </summary>
    public static VcpFeature DisplayControllerType => new(0xC8, "display-controller-type", "Display controller type", VcpFeatureType.ReadOnly, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Display firmware level (VCP 0xC9)
    /// </summary>
    public static VcpFeature DisplayFirmwareLevel => new(0xC9, "display-firmware-level", "Display firmware level", VcpFeatureType.ReadOnly, VcpFeatureCategory.Miscellaneous, false, "firmware");

    /// <summary>
    /// OSD/Button Control (VCP 0xCA)
    /// </summary>
    public static VcpFeature OSDButtonControl => new(0xCA, "osd-button-control", "OSD/Button Control", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false, "osd");

    /// <summary>
    /// OSD Language (VCP 0xCC)
    /// </summary>
    public static VcpFeature OSDLanguage => new(0xCC, "osd-language", "OSD Language", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false, "language");

    /// <summary>
    /// Status Indicators (VCP 0xCD)
    /// </summary>
    public static VcpFeature StatusIndicators => new(0xCD, "status-indicators", "Status Indicators", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Auxiliary display size (VCP 0xCE)
    /// </summary>
    public static VcpFeature AuxiliaryDisplaySize => new(0xCE, "auxiliary-display-size", "Auxiliary display size", VcpFeatureType.ReadOnly, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Auxiliary display data (VCP 0xCF)
    /// </summary>
    public static VcpFeature AuxiliaryDisplayData => new(0xCF, "auxiliary-display-data", "Auxiliary display data", VcpFeatureType.WriteOnly, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Output select (VCP 0xD0)
    /// </summary>
    public static VcpFeature OutputSelect => new(0xD0, "output-select", "Output select", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Asset Tag (VCP 0xD2)
    /// </summary>
    public static VcpFeature AssetTag => new(0xD2, "asset-tag", "Asset Tag", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Power mode (VCP 0xD6)
    /// </summary>
    public static VcpFeature PowerMode => new(0xD6, "power-mode", "Power mode", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false, "power");

    /// <summary>
    /// Auxiliary power output (VCP 0xD7)
    /// </summary>
    public static VcpFeature AuxiliaryPowerOutput => new(0xD7, "auxiliary-power-output", "Auxiliary power output", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// Scratch Pad (VCP 0xDE)
    /// </summary>
    public static VcpFeature ScratchPad => new(0xDE, "scratch-pad", "Scratch Pad", VcpFeatureType.ReadWrite, VcpFeatureCategory.Miscellaneous, false);

    /// <summary>
    /// VCP Version (VCP 0xDF)
    /// </summary>
    public static VcpFeature VcpVersion => new(0xDF, "vcp-version", "VCP Version", VcpFeatureType.ReadOnly, VcpFeatureCategory.Miscellaneous, false, "version");


    // ===== AUDIO FEATURES =====

    /// <summary>
    /// Audio speaker volume (VCP 0x62)
    /// </summary>
    public static VcpFeature AudioVolume => new(0x62, "volume", "Audio speaker volume", VcpFeatureType.ReadWrite, VcpFeatureCategory.Audio, true, "vol");

    /// <summary>
    /// Speaker Select (VCP 0x63)
    /// </summary>
    public static VcpFeature SpeakerSelect => new(0x63, "speaker-select", "Speaker Select", VcpFeatureType.ReadWrite, VcpFeatureCategory.Audio, false);

    /// <summary>
    /// Audio: Microphone Volume (VCP 0x64)
    /// </summary>
    public static VcpFeature MicrophoneVolume => new(0x64, "microphone-volume", "Audio: Microphone Volume", VcpFeatureType.ReadWrite, VcpFeatureCategory.Audio, true, "mic-volume");

    /// <summary>
    /// Audio mute/Screen blank (VCP 0x8D)
    /// </summary>
    public static VcpFeature AudioMute => new(0x8D, "mute", "Audio mute/Screen blank", VcpFeatureType.ReadWrite, VcpFeatureCategory.Audio, false);

    /// <summary>
    /// Audio treble (VCP 0x8F)
    /// </summary>
    public static VcpFeature AudioTreble => new(0x8F, "audio-treble", "Audio treble", VcpFeatureType.ReadWrite, VcpFeatureCategory.Audio, true, "treble");

    /// <summary>
    /// Audio bass (VCP 0x91)
    /// </summary>
    public static VcpFeature AudioBass => new(0x91, "audio-bass", "Audio bass", VcpFeatureType.ReadWrite, VcpFeatureCategory.Audio, true, "bass");

    /// <summary>
    /// Audio balance L/R (VCP 0x93)
    /// </summary>
    public static VcpFeature AudioBalance => new(0x93, "audio-balance", "Audio balance L/R", VcpFeatureType.ReadWrite, VcpFeatureCategory.Audio, true, "balance");

    /// <summary>
    /// Audio processor mode (VCP 0x94)
    /// </summary>
    public static VcpFeature AudioProcessorMode => new(0x94, "audio-processor-mode", "Audio processor mode", VcpFeatureType.ReadWrite, VcpFeatureCategory.Audio, false);


    /// <summary>
    /// All features registry - contains all predefined MCCS features
    /// </summary>
    private static readonly VcpFeature[] _allFeatures = new VcpFeature[]
    {
        Degauss,
        NewControlValue,
        SoftControls,
        RestoreDefaults,
        RestoreBrightnessContrastDefaults,
        RestoreGeometryDefaults,
        RestoreColorDefaults,
        RestoreTVDefaults,
        ColorTemperatureIncrement,
        ColorTemperatureRequest,
        Clock,
        Brightness,
        FleshToneEnhancement,
        Contrast,
        Backlight,
        SelectColorPreset,
        RedGain,
        UserColorVisionCompensation,
        GreenGain,
        BlueGain,
        Focus,
        AutoSetup,
        AutoColorSetup,
        HorizontalPosition,
        HorizontalSize,
        HorizontalPincushion,
        HorizontalPincushionBalance,
        HorizontalConvergenceRB,
        HorizontalConvergenceMG,
        HorizontalLinearity,
        HorizontalLinearityBalance,
        GrayScaleExpansion,
        VerticalPosition,
        VerticalSize,
        VerticalPincushion,
        VerticalPincushionBalance,
        VerticalConvergenceRB,
        VerticalConvergenceMG,
        VerticalLinearity,
        VerticalLinearityBalance,
        ClockPhase,
        HorizontalParallelogram,
        VerticalParallelogram,
        HorizontalKeystone,
        VerticalKeystone,
        Rotation,
        TopCornerFlare,
        TopCornerHook,
        BottomCornerFlare,
        BottomCornerHook,
        ActiveControl,
        PerformancePreservation,
        HorizontalMoire,
        VerticalMoire,
        SixAxisSaturationRed,
        SixAxisSaturationYellow,
        SixAxisSaturationGreen,
        SixAxisSaturationCyan,
        SixAxisSaturationBlue,
        SixAxisSaturationMagenta,
        InputSource,
        AudioVolume,
        SpeakerSelect,
        MicrophoneVolume,
        AmbientLightSensor,
        BacklightLevelWhite,
        RedBlackLevel,
        BacklightLevelRed,
        GreenBlackLevel,
        BacklightLevelGreen,
        BlueBlackLevel,
        BacklightLevelBlue,
        Gamma,
        LUTSize,
        SinglePointLUTOperation,
        BlockLUTOperation,
        RemoteProcedureCall,
        DisplayIdentificationOperation,
        AdjustFocalPlane,
        AdjustZoom,
        Trapezoid,
        Keystone,
        HorizontalMirror,
        VerticalMirror,
        DisplayScaling,
        Sharpness,
        VelocityScanModulation,
        ColorSaturation,
        TVChannelUpDown,
        TVSharpness,
        AudioMute,
        TVContrast,
        AudioTreble,
        Hue,
        AudioBass,
        TVBlackLevel,
        AudioBalance,
        AudioProcessorMode,
        WindowPositionTLX,
        WindowPositionTLY,
        WindowPositionBRX,
        WindowPositionBRY,
        WindowControlOnOff,
        WindowBackground,
        SixAxisHueRed,
        SixAxisHueYellow,
        SixAxisHueGreen,
        SixAxisHueCyan,
        SixAxisHueBlue,
        SixAxisHueMagenta,
        AutoSetupOnOff,
        WindowMaskControl,
        ChangeSelectedWindow,
        ScreenOrientation,
        HorizontalFrequency,
        VerticalFrequency,
        Settings,
        FlatPanelSubPixelLayout,
        SourceTimingMode,
        DisplayTechnologyType,
        MonitorStatus,
        PacketCount,
        MonitorXOrigin,
        MonitorYOrigin,
        HeaderErrorCount,
        BodyCRCErrorCount,
        ClientID,
        LinkControl,
        DisplayUsageTime,
        DisplayDescriptorLength,
        TransmitDisplayDescriptor,
        EnableDisplayOfDisplayDescriptor,
        ApplicationEnableKey,
        DisplayControllerType,
        DisplayFirmwareLevel,
        OSDButtonControl,
        OSDLanguage,
        StatusIndicators,
        AuxiliaryDisplaySize,
        AuxiliaryDisplayData,
        OutputSelect,
        AssetTag,
        StereoVideoMode,
        PowerMode,
        AuxiliaryPowerOutput,
        ScanMode,
        ImageMode,
        DisplayMode,
        ScratchPad,
        VcpVersion
    };

    public static IReadOnlyList<VcpFeature> AllFeatures => _allFeatures;
}
